name: Generate JSON
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      
      - name: Setup Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      
      - name: Generate JSON
        run: |
          python generate.py "${{ secrets.GITHUB_TOKEN }}" > modules.json
          
      - name: Commit Changes
        run: |
          git config --global user.email "mmar-json@users.noreply.github.com"
          git config --global user.name "mmar-json"
          git add modules.json
          git commit -sm "Update modules.json" || true
          git push || true
